FROM debian

RUN apt-get update
RUN apt install -yy openjdk-17-jre libreadline8 libncursesw5 procps unzip
RUN ln -s /lib/x86_64-linux-gnu/libreadline.so.8 /lib/x86_64-linux-gnu/libreadline.so.6

RUN useradd -md /cb cb
USER cb

COPY cb/CBinstaller.jar /cb/
WORKDIR /cb
RUN unzip CBinstaller.jar
RUN bash ./make-executable
RUN mkdir cbdata
RUN mkdir cbexport

VOLUME ["/cb/cbdata", "/cb/cbexport"]
